### PR TITLE
S3 storage

### PR DESCRIPTION
**Pull request by normaljosh**
Not sure this is necessary as-is,  but wanted to discuss on wednesday. I created a bucket we could share to. I'll message the keys (which would go in the aws_creds.py file). 

Instead of storing every html file, we might want to consider combining them somehow into a larger file (gzip or just json)

### CODE REVIEW

**Review by derac — APPROVED** [review]
looks good, merging. will add a mode parameter that defaults to local

**Comment by derac** [comment]
more difficult to commit than I'd anticipated. Can you try to merge with the latest branch and switch between local and s3 via argparse? Yeah, if you are uploading to s3, I would recommend zipping the JSON files from the case parser and only uploading those.

**Comment by derac** [comment]
For reference, 2 months of all data for all included JOs is 92.6 MB uncompressed. The JSON is 10.2 MB uncompressed.

**Comment by derac** [comment]
TBH, might be easier to just grab the local files and upload to s3 through some other means.

**Comment by derac** [comment]
If you wanted to organize multiple people running the script, perhaps you could partition the date ranges that the scrape_calendar_data.py script is operating on.

**Comment by derac** [comment]
Actually it'd be nice to have an AWS switch in the JSON parser (process_case_date.py), which checks if the JSON file is already there (same case code), and if so, checks if it's newer before replacing it (date field in the case JSON). + zip on read/write

**Comment by derac** [comment]
If you are writing a bunch of files that are already there this will incur a bunch of reads though.

**Comment by derac** [comment]
Haha sorry for the spam, was just thinking this out. We could put the date in the filename to avoid merge conflicts without reading the json.

**Comment by derac** [comment]
Can you implement this as a new file that operates on the JSON output of the last step and parses the correct name (code+date), checks dates against s3 for merging (don't upload if not newer), zips, and uploads to AWS? `./src/upload_to_aws.py` + `./src/libraries/aws_config.py`

**Comment by normaljosh** [comment]
Yep, something like that was basically going to be my suggestion, or maybe making a large json per month or year or whatever by each judge, where key is date and value is html (since files themselves wouldn't be that big.)

Won't be able to take a look at this again until Wednesday's CAN, but we can talk about options then

**Pull request closed without merging**
